server:
  port: ${test.eureka.server.port}    # 指定该Eureka实例的端⼝

spring:
  profiles: test

eureka:
  environment: test
  datacenter: linux
  server:
    enable-self-preservation: true  # 关闭自我保护
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    #    prefer-ip-address: true   # 这个设置成true后， unavailable-replicas '异常'
    hostname: ${test.eureka.hostname}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}
    ip-address: 172.21.247.53
  client:
    serviceUrl:
      defaultZone: http://${test.eureka.hostname}:${test.eureka.server.port}/eureka/
    registerWithEureka: false  # 单机模式 设置为false
    fetchRegistry: false       # 单机模式 设置为false


security:
  basic:
    enabled: false
    path: ${management.context-path}
  user:
    name: bee_admin
    password: asdqwe123!@#